FROM node:alpine

ARG puerto
RUN mkdir /var/test
WORKDIR /var/test
COPY package.json /var/test/
RUN npm install && npm install -g mocha
COPY src/ /var/test/
CMD ["mocha", "tests/unitTests/", puerto, "--recursive", "&&", "mocha", "--exit"]