FROM node:carbon 
WORKDIR ./ 
COPY ./package.json ./package-lock.json ./src ./
RUN npm install && npm install -g mocha && npm install -g codeceptjs
RUN node src/index.js
CMD ["codeceptjs", "run", "--steps", "--verbose", "--config=./src/tests/e2eTests/config.js" ]