version: "2"
services:
  app:
    container_name: app  
    build:
      context: .
      dockerfile: Dockerfile.e2e
    ports:
      - "4000:4000"   
    depends_on:
      - firefox-container
    volumes:
      - ./e2eTests:/e2eTests
      - ./package.json:/package.json
      - ./package-lock.json:/package-lock.json
      - ./.gitignore:/.gitignore
      - ./src/index.js:/src/index.js

  firefox-container:
    container_name: firefox-container
    image: selenium/standalone-firefox:3.12.0-americium
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"